const ERRORS = {
    noPasswordMatch: "Password doesn't match!!!",
    noLikeByUser: "Not liked by this user",
    alreadyLiked: "Already Liked by user",
    noUser : "User doesn't Exist!!",
    noTid : "There is no Tweet id i.e., uid",
    noUid : "There is no user id i.e., uid",
    noPageSize : "Didn't get page size",
    noPageNo : "Didn;t get page number",
    noComment : "There is no comment",
    noTweetExist : "No such Tweet id exist",
    noUserExists : "No such user id exist",
    noTweet : "There is no tweet to add",
    noTweetId : "No tweet id",
    someFieldsMissing : "Something is missing out of required fields",
    alreadyInRelation : "Users already have a relationship",
    friendRequestSent : "Friend Request Sent!!",
    alreadyFriend : "Friendship request done, can only accept or reject",
    noFriends : "No friends to show ",
    noRelation : "No relation between users",
    InRelation : "Relation Exists",
    noUser : "User doesn't Exist!!",
    noUpdateType : "No Type to update",
    noID : "There is no ID",
    noEmail : "There is no email to add",
    noPassword : "There is no password to add",
    noName : "No name to add",
    noUserId : "No user id",
    noNewPassword : "There is no new password to change",
    dbError : "Something wrong with the query or Database"
}

module.exports = { ERRORS }