const TEXT = {}

TEXT.noTid = "There is no Tweet id i.e., uid"
TEXT.noUid = "There is no user id i.e., uid"
TEXT.noPageSize = "Didn't get page size"
TEXT.noPageNo = "Didn;t get page number"
TEXT.noComment = "There is no comment"
TEXT.noTweetExist = "No such Tweet id exist"
TEXT.noUserExists = "No such user id exist"
TEXT.noTweet = "There is no tweet to add"
TEXT.noTweetId = "No tweet id",
TEXT.someFieldsMissing = "Something is missing out of required fields"
TEXT.alreadyInRelation = "Users already have a relationship"
TEXT.friendRequestSent = "Friend Request Sent!!"
TEXT.alreadyFriend = "Friendship request done, can only accept or reject"
TEXT.noFriends = "No friends to show "
TEXT.noRelation = "No relation between users"
TEXT.InRelation = "Relation Exists"
TEXT.noUser = "User doesn't Exist!!"
TEXT.noUpdateType = "No Type to update"
TEXT.noID = "There is no ID"
TEXT.noEmail = "There is no email to add"
TEXT.noPassword = "There is no password to add"
TEXT.noName = "No name to add"
TEXT.noUserId = "No user id"
TEXT.noNewPassword = "There is no new password to change"
TEXT.entityTweet = 'tweet'
TEXT.entityComment = 'comment'
TEXT.likeTypeLike = 'like'
TEXT.likeTypeLove = 'love'
TEXT.likeTypeHappy = 'happy'
TEXT.likeTypeSad = 'sad'
TEXT.likeTypeCurious = 'curious'

module.exports = {TEXT}
